<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MKelurahan extends CI_Model
{

    public $table = 'kelurahan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get field
    function get_field(){
      return $this->db->list_fields($this->table);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('id_kecamatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function getJoin($id_kota){
      $sql="SELECT `kota`.`id` as `id_kota`,`kelurahan`.`id` as `id_kelurahan`,`kelurahan`.`nama` as `nama_kelurahan`,`kecamatan`.`id` as `id_kecamatan`,`kecamatan`.`nama` as `nama_kecamatan`
      FROM `kota` INNER JOIN `kecamatan` ON `kota`.`id`= `kecamatan`.`id_kota`
      INNER JOIN `kelurahan` ON `kecamatan`.`id`=`kelurahan`.`id_kecamatan` WHERE `kota`.`id`=$id_kota";
      return $this->db->query($sql)->result();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('id_kecamatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MKelurahan.php */
/* Location: ./application/models/MKelurahan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-29 14:06:07 */
/* http://harviacode.com */
