<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_wisata_model extends CI_Model
{

    public $table = 'data_wisata';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get field
    function get_field(){
      return $this->db->list_fields($this->table);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_id_user($id_user)
    {
        $this->db->where('id_user', $id_user);
        $this->db->where('safe_delete!=', 1);
        return $this->db->get($this->table)->result();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lang', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('harga_tiket', $q);
	$this->db->or_like('peta_marker', $q);
	$this->db->or_like('id_kota', $q);
	$this->db->or_like('id_kecamatan', $q);
	$this->db->or_like('id_kelurahan', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('safe_delete', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('htm_dewasa', $q);
	$this->db->or_like('htm_anak', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lang', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('harga_tiket', $q);
	$this->db->or_like('peta_marker', $q);
	$this->db->or_like('id_kota', $q);
	$this->db->or_like('id_kecamatan', $q);
	$this->db->or_like('id_kelurahan', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('safe_delete', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('htm_dewasa', $q);
	$this->db->or_like('htm_anak', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function safe_delete($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Data_wisata_model.php */
/* Location: ./application/models/Data_wisata_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-29 13:06:49 */
/* http://harviacode.com */
